{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "873b5095",
   "metadata": {},
   "outputs": [],
   "source": [
    "import win32com.client as wc\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "81b35d4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def static_mixer(radius, L_insert, h, file_name):\n",
    "    '''This function creates just one helical insert of the static mixer. \n",
    "    radius - inner radius of the pipe\n",
    "    L_insert - length of one insert\n",
    "    h - thickness of the insert\n",
    "    file_name - to save the file\n",
    "    \n",
    "    TO DO:\n",
    "    function for smoothing the sweep guide rail\n",
    "    mirror/pattern/loop for creation of the whole static mixer\n",
    "    '''\n",
    "    inv_app = wc.GetActiveObject(\"Inventor.Application\")\n",
    "\n",
    "    # Create a new part document\n",
    "    part_doc = inv_app.Documents.Add(12290, inv_app.FileManager.GetTemplateFile(12290, 8962))\n",
    "    #part_doc = inv_app.Documents.Add(\"Part\", inv_app.FileManager.GetTemplateFile(\"Part\"), True)\n",
    "    comp_def = part_doc.ComponentDefinition\n",
    "    \n",
    "    # Create a 2D sketch for the tool body profile on the X-Y plane\n",
    "    xy_plane = comp_def.WorkPlanes.Item(3) \n",
    "    profile_sketch = comp_def.Sketches.Add(xy_plane)\n",
    "    radius = 1\n",
    "    L_insert = 10\n",
    "    # Define a rectangular profile for the tool body\n",
    "    transient_geom = inv_app.TransientGeometry\n",
    "    profile_sketch.SketchLines.AddAsTwoPointRectangle(\n",
    "        transient_geom.CreatePoint2d(2*radius, h/2), \n",
    "        transient_geom.CreatePoint2d(-2*radius, -h/2) \n",
    "    )\n",
    "\n",
    "    # Create a base feature from the profile to form the tool body\n",
    "    profile = profile_sketch.Profiles.AddForSolid()\n",
    "    \n",
    "    cyl_sketch = comp_def.Sketches.Add(xy_plane)\n",
    "    center = transient_geom.CreatePoint2d(0,0)\n",
    "    cyl_sketch.SketchCircles.AddByCenterRadius(center, radius)\n",
    "\n",
    "    cyl_profile = cyl_sketch.Profiles.AddforSolid()\n",
    "    ext_solid_def = comp_def.Features.ExtrudeFeatures.CreateExtrudeDefinition(cyl_profile, 20481)\n",
    "    ext_solid_def.SetDistanceExtent(L_insert, 20993)\n",
    "    cyl_solid = comp_def.Features.ExtrudeFeatures.Add(ext_solid_def)\n",
    "    \n",
    "    plane = comp_def.Sketches.Add(comp_def.WorkPlanes.Item(3))\n",
    "\n",
    "    comp_def.WorkPlanes.AddByPlaneAndOffset(plane, L_insert)\n",
    "    \n",
    "    sketch_mid = comp_def.Sketches.Add(comp_def.WorkPlanes.Item(4)) # new sketch\n",
    "    \n",
    "    sketch_mid.SketchLines.AddAsTwoPointRectangle(\n",
    "    transient_geom.CreatePoint2d(2*radius, h/2),\n",
    "    transient_geom.CreatePoint2d(-2*radius, -h/2))\n",
    "    \n",
    "    profile_mid = sketch_mid.Profiles.AddForSolid()\n",
    "    \n",
    "    rail_sketch = comp_def.Sketches3D.Add()\n",
    "    oWPs1 = comp_def.WorkPoints.AddFixed(transient_geom.CreatePoint(2*radius, h/2, 0))\n",
    "    oWPs2 = comp_def.WorkPoints.AddFixed(transient_geom.CreatePoint(-h/2, 2*radius, L_insert/2))\n",
    "    oWPs3 = comp_def.WorkPoints.AddFixed(transient_geom.CreatePoint(-2*radius, -h/2, L_insert))\n",
    "    oStartLine3d = rail_sketch.SketchLines3D.AddByTwoPoints(oWPs1, oWPs2)\n",
    "    oLine3D = rail_sketch.SketchLines3D.AddByTwoPoints(oStartLine3d.EndSketchPoint, oWPs3)\n",
    "    rail = comp_def.Features.CreatePath(oLine3D)\n",
    "    \n",
    "    path_sketch = comp_def.Sketches3D.Add()\n",
    "    opath = path_sketch.SketchLines3D.AddByTwoPoints(\n",
    "        transient_geom.CreatePoint(0, 0, 0),\n",
    "        transient_geom.CreatePoint(0, 0, L_insert)\n",
    "    )\n",
    "\n",
    "    # Create the path object from the 3D sketch\n",
    "    path = comp_def.Features.CreatePath(opath)\n",
    "    \n",
    "    sweep_def = comp_def.Features.SweepFeatures.CreateSweepDefinition(104450,profile, path, 20482)\n",
    "    \n",
    "    sweep_def.GuideRail = rail\n",
    "    sweep_feature = comp_def.Features.SweepFeatures.Add(sweep_def)\n",
    "    \n",
    "    inv_app.ActiveDocument.SaveAs(f\"D:\\\\Python Projects\\\\Inventor\\\\{file_name}.ipt\", False)\n",
    "    \n",
    "    return None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "dd7710e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "geom = static_mixer(1, 1.5, 0.2, 'mixer1') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8a02747",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
